version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/definitions.json:/opt/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NAME=rabbitmq
  tests:
    depends_on:
      rabbitmq:
        condition: service_started
    image: node
    volumes:
    - .:/service
    working_dir: /service
    environment:
      - RABBITMQ_URI=amqp://deploy_user:guest@rabbitmq/test
