version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.10.1-management-alpine
    volumes:
      - ./rabbitmq/definitions.json:/opt/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NAME=rabbitmq
  tests:
    image: node
    depends_on:
      - consumer
    volumes:
    - .:/service
    working_dir: /service
    environment:
      - RABBITMQ_URL=amqp://username:password@rabbitmq
  consumer:
    image: calvinmo/ntd2022
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_URL=amqp://username:password@rabbitmq